//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppConfiguration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BgEngine.Resources.AppConfiguration", typeof(AppConfiguration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string Admin_Role {
            get {
                return ResourceManager.GetString("Admin_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string Categories_Number_of_Categories_per_Page {
            get {
                return ResourceManager.GetString("Categories_Number_of_Categories_per_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string Comments_Number_of_Comments_per_Page {
            get {
                return ResourceManager.GetString("Comments_Number_of_Comments_per_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © BgEngine 2011.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Dark_Background_Themes {
            get {
                return ResourceManager.GetString("Dark_Background_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aristo;Rocket;Cobalt.
        /// </summary>
        public static string Dark_Header_Themes {
            get {
                return ResourceManager.GetString("Dark_Header_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobalt.
        /// </summary>
        public static string Default_Theme {
            get {
                return ResourceManager.GetString("Default_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Files/Temp_Data/.
        /// </summary>
        public static string Directories_Temp_Data {
            get {
                return ResourceManager.GetString("Directories_Temp_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7HogarthRoad.
        /// </summary>
        public static string Email_Password {
            get {
                return ResourceManager.GetString("Email_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yawette@hotmail.com.
        /// </summary>
        public static string Email_UserName {
            get {
                return ResourceManager.GetString("Email_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA-24574598-1.
        /// </summary>
        public static string Google_Analytics_Track_Code {
            get {
                return ResourceManager.GetString("Google_Analytics_Track_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string Index_Number_of_Posts {
            get {
                return ResourceManager.GetString("Index_Number_of_Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Icons/logo.jpg.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Icons/no_image.jpg.
        /// </summary>
        public static string No_Image {
            get {
                return ResourceManager.GetString("No_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string Posts_Number_of_Posts_per_Page {
            get {
                return ResourceManager.GetString("Posts_Number_of_Posts_per_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to premium.
        /// </summary>
        public static string Premium_Role {
            get {
                return ResourceManager.GetString("Premium_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6LdofcQSAAAAAMGb119SbYgX18pwtPnPbBNk1tMH.
        /// </summary>
        public static string Recaptcha_Private_Key_Http {
            get {
                return ResourceManager.GetString("Recaptcha_Private_Key_Http", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6LdqfcQSAAAAAKqgoeIUNlYbOJFHM3rhia2kpbRW.
        /// </summary>
        public static string Recaptcha_Private_Key_localhost {
            get {
                return ResourceManager.GetString("Recaptcha_Private_Key_localhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6LdofcQSAAAAAEw0fhwatfkTAJJlYEyjlCTrgKKm.
        /// </summary>
        public static string Recaptcha_Public_Key_Http {
            get {
                return ResourceManager.GetString("Recaptcha_Public_Key_Http", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6LdqfcQSAAAAAHP4vF9uTfxmao2C4e8oYOoT1_dK.
        /// </summary>
        public static string Recaptcha_Public_Key_localhost {
            get {
                return ResourceManager.GetString("Recaptcha_Public_Key_localhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string Roles_Number_of_Roles_per_Page {
            get {
                return ResourceManager.GetString("Roles_Number_of_Roles_per_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string SearchImages_Number_of_Images_per_Page {
            get {
                return ResourceManager.GetString("SearchImages_Number_of_Images_per_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string SearchVideos_Number_of_Videos_per_Page {
            get {
                return ResourceManager.GetString("SearchVideos_Number_of_Videos_per_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BgEngine.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.BgEngine.
        /// </summary>
        public static string SiteUrl {
            get {
                return ResourceManager.GetString("SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string Smtp_Port {
            get {
                return ResourceManager.GetString("Smtp_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.live.com.
        /// </summary>
        public static string Smtp_Server {
            get {
                return ResourceManager.GetString("Smtp_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string Tags_Number_of_Tags_per_Page {
            get {
                return ResourceManager.GetString("Tags_Number_of_Tags_per_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150.
        /// </summary>
        public static string ThumbnailHeight {
            get {
                return ResourceManager.GetString("ThumbnailHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string ThumbnailWidth {
            get {
                return ResourceManager.GetString("ThumbnailWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string Users_Number_of_Users_per_Page {
            get {
                return ResourceManager.GetString("Users_Number_of_Users_per_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 160.
        /// </summary>
        public static string Video_Container_Height {
            get {
                return ResourceManager.GetString("Video_Container_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250.
        /// </summary>
        public static string Video_Container_Width {
            get {
                return ResourceManager.GetString("Video_Container_Width", resourceCulture);
            }
        }
    }
}
