//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BgEngine.Resources.EmailTemplates", typeof(EmailTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Como restablecer tu cuenta?.
        /// </summary>
        public static string PasswordReset_Explanation {
            get {
                return ResourceManager.GetString("PasswordReset_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablece tu cuenta con el siguiente link.
        /// </summary>
        public static string PasswordReset_ExplanationContent {
            get {
                return ResourceManager.GetString("PasswordReset_ExplanationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to para restablecer tu cuenta.
        /// </summary>
        public static string PasswordReset_Restart {
            get {
                return ResourceManager.GetString("PasswordReset_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación de restablecimiento de cuenta en {0}.
        /// </summary>
        public static string PasswordReset_Subject {
            get {
                return ResourceManager.GetString("PasswordReset_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablece tu cuenta mediante el enlace proporcionado a continuación.
        /// </summary>
        public static string PasswordReset_SubTitle {
            get {
                return ResourceManager.GetString("PasswordReset_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablece tu cuenta!.
        /// </summary>
        public static string PasswordReset_Title {
            get {
                return ResourceManager.GetString("PasswordReset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para asegurar que recibes los mensajes procedentes de este sitio en tu bandeja de entrada, añade esta dirección de mail a tu libreta de direcciones o lista de contactos.
        /// </summary>
        public static string RegisterMail_AdddUsContent {
            get {
                return ResourceManager.GetString("RegisterMail_AdddUsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadenos a tu libreta de direcciones.
        /// </summary>
        public static string RegisterMail_AddUs {
            get {
                return ResourceManager.GetString("RegisterMail_AddUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienes alguna duda?.
        /// </summary>
        public static string RegisterMail_AnyQuestions {
            get {
                return ResourceManager.GetString("RegisterMail_AnyQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dudes en contestar a este mail si tienes alguna duda acerca de los mensajes que recibes de este sitio.
        /// </summary>
        public static string RegisterMail_AnyQuestionsContent {
            get {
                return ResourceManager.GetString("RegisterMail_AnyQuestionsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma tu cuenta manualmente.
        /// </summary>
        public static string RegisterMail_ConfirmationLink {
            get {
                return ResourceManager.GetString("RegisterMail_ConfirmationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de confirmación:.
        /// </summary>
        public static string RegisterMail_ConfirmationToken {
            get {
                return ResourceManager.GetString("RegisterMail_ConfirmationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si no puedes confirmar tu cuenta mediante el link proporcionado, puedes hacerlo manualmente en la siguiente dirección usando el código de confirmación que puedes ver un poco más arriba:.
        /// </summary>
        public static string RegisterMail_ConfirmationTokenMessage {
            get {
                return ResourceManager.GetString("RegisterMail_ConfirmationTokenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus datos se han guardado correctamente:.
        /// </summary>
        public static string RegisterMail_DataSaved {
            get {
                return ResourceManager.GetString("RegisterMail_DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string RegisterMail_Email {
            get {
                return ResourceManager.GetString("RegisterMail_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienes alguna idea para ayudarnos a mejorar nuestro sitio?.
        /// </summary>
        public static string RegisterMail_Ideas {
            get {
                return ResourceManager.GetString("RegisterMail_Ideas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estaría encantado de escucharla!.  Envíame un mail si tienes alguna idea o sugerencia para ayudarme a mejorar mi página.
        /// </summary>
        public static string RegisterMail_IdeasContent {
            get {
                return ResourceManager.GetString("RegisterMail_IdeasContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulsa el siguiente link.
        /// </summary>
        public static string RegisterMail_PressLink {
            get {
                return ResourceManager.GetString("RegisterMail_PressLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muchas gracias y un saludo,.
        /// </summary>
        public static string RegisterMail_Regards {
            get {
                return ResourceManager.GetString("RegisterMail_Regards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación de registro en {0}.
        /// </summary>
        public static string RegisterMail_Subject {
            get {
                return ResourceManager.GetString("RegisterMail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ahora has de confirmar la cuenta pulsando el link ....
        /// </summary>
        public static string RegisterMail_SubTitle {
            get {
                return ResourceManager.GetString("RegisterMail_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma el registro!.
        /// </summary>
        public static string RegisterMail_Title {
            get {
                return ResourceManager.GetString("RegisterMail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to para confirmar el registro.
        /// </summary>
        public static string RegisterMail_ToConfirm {
            get {
                return ResourceManager.GetString("RegisterMail_ToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario:.
        /// </summary>
        public static string RegisterMail_User {
            get {
                return ResourceManager.GetString("RegisterMail_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido!.
        /// </summary>
        public static string RegisterMail_Welcome {
            get {
                return ResourceManager.GetString("RegisterMail_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este mail se ha enviado a {0} porque has decidido crear una cuenta en {1}.
        /// </summary>
        public static string RegisterMail_WhySent {
            get {
                return ResourceManager.GetString("RegisterMail_WhySent", resourceCulture);
            }
        }
    }
}
